export const projects = [
  {
    id: 1,
    name: "CryptoFlow",
    description:
      "A crypto-focused web app that aggregates live news from multiple sources and provides built-in portfolio tracking, helping users stay informed and manage their assets in one place. Built with React, TypeScript, TailwindCSS, and a Node.js/Express backend, the project deepened my understanding of TanStack Query v5 and refreshed my backend skills through hands-on debugging, optimization, and real-world data handling.",
    link: "https://crypto-flow-nine.vercel.app",
    image: "/assets/notely.png",
    logo: "/assets/cryptoflow-logo.ico",
    screenshot: "/assets/cryptoflow-bg.png",
    tags: [
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Local Storage",
      "Responsive Design",
      "Node.js",
      "Express.js",
      "News API",
      "CoinGecko API",
      "TanStack Query v5",
    ],
  },
  {
    id: 2,
    name: "MovieBox",
    description:
      " Discover the magic of cinema with my React-based movie details website. Seamlessly navigate through an extensive collection of films, exploring synopses, cast details, ratings, and more. With an intuitive user interface and responsive design, users can effortlessly dive into their favorite movies from any device. Elevating the movie-watching experience, this website is a testament to my passion for both web development and love for movies.",
    link: "https://movieinfo-2.vercel.app",
    image: "/assets/movieinfo.png",
    logo: "/assets/movieinfo-logo.png",
    screenshot: "/assets/movieinfo-bg.png",
    tags: ["HTML", "CSS", "JavaScript", "React", "Tailwind CSS", "Supabase"],
  },
  {
    id: 3,
    name: "RoomRadar",
    description:
      "A campus lodge-finding web app that helps students discover available accommodations around their campus with ease. Built using React, TailwindCSS, shadcn/ui, and a Node.js/Express backend with MongoDB, I collaborated within a team and contributed primarily to the backend, focusing on API development, database modeling, and ensuring smooth data flow between the server and frontend..",
    link: "https://roomradar-frontend.vercel.app",
    image: "/assets/the-autoscript.png",
    logo: "/assets/room-radar-logo.png",
    screenshot: "/assets/room-radar-bg.png",
    tags: [
      "React",
      "Tailwind CSS",
      "TypeScript",
      "Shadcn",
      "Node.js",
      "Express.js",
      "MongoDB",
    ],
  },
  {
    id: 4,
    name: "Atmosync",
    description:
      "Atmosync is a modern weather forecast web app that delivers real-time conditions, hourly and 7-day forecasts, and location-aware insights through a clean, responsive interface. It combines accurate weather APIs with intuitive data visualization to help users plan their day confidently—whether checking commute conditions, weekend outlooks, or severe weather alerts. Built with a performance-first approach, Atmosync highlights my ability to design user-focused experiences, integrate external APIs, and build scalable frontend architecture.",
    link: "https://weather-app-xi-liart.vercel.app",
    image: "/assets/atmosync.png",
    logo: "/assets/atmosync-logo.jpg",
    screenshot: "/assets/atmosync-bg.png",
    tags: [
      "React",
      "Tailwind CSS",
      "TypeScript",
      "FireStore",
      "Firebase Auth",
      "OpenWeather API",
      "Geolocation API",
    ],
  },
];
